### ISSUE TITLE
登录后运行闪退，提示出现缺少MapSDK

### ISSUE THREAD

**Issue by phoenixsfly** [chuanggaofucker/ChuangGaoFuckerApp#2]
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-8
                  Process: net.crigh.cgsport, PID: 19692
                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/net.crigh.cgsport-DTuWIGIjmsn3e77Tqq5gTw==/base.apk", zip file "/data/app/net.crigh.cgsport-DTuWIGIjmsn3e77Tqq5gTw==/split_lib_dependencies_apk.apk", zip file "/data/app/net.crigh.cgsport-DTuWIGIjmsn3e77Tqq5gTw==/split_lib_resources_apk.apk", zip file "/data/app/net.crigh.cgsport-DTuWIGIjmsn3e77Tqq5gTw==/split_lib_slice_0_apk.apk", zip file "/data/app/net.crigh.cgsport-DTuWIGIjmsn3e77Tqq5gTw==/split_lib_slice_1_apk.apk", zip file "/data/app/net.crigh.cgsport-DTuWIGIjmsn3e77Tqq5gTw==/split_lib_slice_2_apk.apk", zip file "/data/app/net.crigh.cgsport-DTuWIGIjmsn3e77Tqq5gTw==/split_lib_slice_3_apk.apk", zip file "/data/app/net.crigh.cgsport-DTuWIGIjmsn3e77Tqq5gTw==/split_lib_slice_4_apk.apk", zip file "/data/app/net.crigh.cgsport-DTuWIGIjmsn3e77Tqq5gTw==/split_lib_slice_5_apk.apk", zip file "/data/app/net.crigh.cgsport-DTuWIGIjmsn3e77Tqq5gTw==/split_lib_slice_6_apk.apk", zip file "/data/app/net.crigh.cgsport-DTuWIGIjmsn3e77Tqq5gTw==/split_lib_slice_7_apk.apk", zip file "/data/app/net.crigh.cgsport-DTuWIGIjmsn3e77Tqq5gTw==/split_lib_slice_8_apk.apk", zip file "/data/app/net.crigh.cgsport-DTuWIGIjmsn3e77Tqq5gTw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/net.crigh.cgsport-DTuWIGIjmsn3e77Tqq5gTw==/lib/arm64, /system/lib64, /product/lib64]]] couldn't find "libAMapSDK_Location_v6_6_0.so"
                      at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
                      at java.lang.System.loadLibrary(System.java:1672)
                      at net.crigh.api.encrypt.ChingoEncrypt.<clinit>(ChingoEncrypt.java:12)
                      at net.crigh.api.encrypt.ChingoEncrypt.cgapiEnrypt(Native Method)
                      at net.crigh.api.service.NetworkService.run(NetworkService.java:183)
                      at net.crigh.cgsport.cgactivity.ChingoSportActivity.lambda$null$1$ChingoSportActivity(ChingoSportActivity.java:106)
                      at net.crigh.cgsport.cgactivity.ChingoSportActivity$$Lambda$5.run(Unknown Source:26)
                      at java.lang.Thread.run(Thread.java:784)
```
运行环境 华为荣耀V10; Android 9.0; API 28

**Comment by chuanggaofucker** [comment]
非常抱歉我忘记引入某个.so文件了，现在应该可以啦。
